# ---------------- COMPLETE LANGUAGE MAP (ONLY GOOGLE TRANSLATE SUPPORTED LANGUAGES) ----------------
# All languages below are VERIFIED from Google Translate's official list
LANG_MAP = {
    # === SOUTH ASIAN LANGUAGES ===
    "hindi": ("hi", "hi-IN-MadhurNeural"),
    "english": ("en", "en-US-AriaNeural"),
    "sanskrit": ("sa", "hi-IN-MadhurNeural"),
    "gujarati": ("gu", "gu-IN-DhwaniNeural"),
    "bengali": ("bn", "bn-IN-TanishaaNeural"),
    "tamil": ("ta", "ta-IN-PallaviNeural"),
    "telugu": ("te", "te-IN-ShrutiNeural"),
    "marathi": ("mr", "mr-IN-AarohiNeural"),
    "kannada": ("kn", "kn-IN-SapnaNeural"),
    "malayalam": ("ml", "ml-IN-SobhanaNeural"),
    "punjabi": ("pa", "pa-IN-OjaasNeural"),
    "urdu": ("ur", "ur-PK-AsadNeural"),
    "odia": ("or", "or-IN-SubasisNeural"),
    "assamese": ("as", "as-IN-PriyomNeural"),
    "sindhi": ("sd", "hi-IN-MadhurNeural"),
    "nepali": ("ne", "ne-NP-HemkalaNeural"),
    "sinhala": ("si", "si-LK-SameeraNeural"),
    "maithili": ("mai", "hi-IN-MadhurNeural"),
    "dogri": ("doi", "hi-IN-MadhurNeural"),
    "kashmiri": ("ks", "hi-IN-MadhurNeural"),
    "konkani": ("gom", "hi-IN-MadhurNeural"),
    "bodo": ("brx", "hi-IN-MadhurNeural"),
    "santhali": ("sat", "hi-IN-MadhurNeural"),
    "bhojpuri": ("bho", "hi-IN-MadhurNeural"),
    "dhivehi": ("dv", "hi-IN-MadhurNeural"),

    # === EAST ASIAN LANGUAGES ===
    "chinese simplified": ("zh-CN", "zh-CN-XiaoxiaoNeural"),
    "chinese traditional": ("zh-TW", "zh-TW-HsiaoChenNeural"),
    "japanese": ("ja", "ja-JP-NanamiNeural"),
    "korean": ("ko", "ko-KR-SunHiNeural"),
    "mongolian": ("mn", "mn-MN-BataaNeural"),
    "tibetan": ("bo", "hi-IN-MadhurNeural"),

    # === SOUTHEAST ASIAN LANGUAGES ===
    "thai": ("th", "th-TH-PremwadeeNeural"),
    "vietnamese": ("vi", "vi-VN-HoaiMyNeural"),
    "indonesian": ("id", "id-ID-GadisNeural"),
    "malay": ("ms", "ms-MY-YasminNeural"),
    "filipino": ("tl", "fil-PH-AngeloNeural"),
    "khmer": ("km", "km-KH-SreymomNeural"),
    "lao": ("lo", "lo-LA-KeomanyNeural"),
    "myanmar burmese": ("my", "my-MM-ThihaNeural"),
    "javanese": ("jw", "jv-ID-SitiNeural"),
    "sundanese": ("su", "su-ID-TutiNeural"),
    "cebuano": ("ceb", "en-US-AriaNeural"),
    "hmong": ("hmn", "en-US-AriaNeural"),

    # === EUROPEAN LANGUAGES ===
    "french": ("fr", "fr-FR-DeniseNeural"),
    "german": ("de", "de-DE-KatjaNeural"),
    "spanish": ("es", "es-ES-ElviraNeural"),
    "italian": ("it", "it-IT-ElsaNeural"),
    "portuguese": ("pt", "pt-BR-FranciscaNeural"),
    "russian": ("ru", "ru-RU-DmitryNeural"),
    "ukrainian": ("uk", "uk-UA-PolinaNeural"),
    "polish": ("pl", "pl-PL-ZofiaNeural"),
    "dutch": ("nl", "nl-NL-ColetteNeural"),
    "greek": ("el", "el-GR-AthinaNeural"),
    "turkish": ("tr", "tr-TR-EmelNeural"),
    "swedish": ("sv", "sv-SE-SofieNeural"),
    "norwegian": ("no", "nb-NO-PernilleNeural"),
    "danish": ("da", "da-DK-ChristelNeural"),
    "finnish": ("fi", "fi-FI-NooraNeural"),
    "czech": ("cs", "cs-CZ-VlastaNeural"),
    "romanian": ("ro", "ro-RO-AlinaNeural"),
    "hungarian": ("hu", "hu-HU-NoemiNeural"),
    "bulgarian": ("bg", "bg-BG-BorislavNeural"),
    "croatian": ("hr", "hr-HR-GabrijelaNeural"),
    "serbian": ("sr", "sr-RS-NicholasNeural"),
    "slovak": ("sk", "sk-SK-ViktoriaNeural"),
    "slovenian": ("sl", "sl-SI-PetraNeural"),
    "estonian": ("et", "et-EE-AnuNeural"),
    "latvian": ("lv", "lv-LV-EveritaNeural"),
    "lithuanian": ("lt", "lt-LT-OnaNeural"),
    "albanian": ("sq", "sq-AL-IlirNeural"),
    "macedonian": ("mk", "mk-MK-MarijaNeural"),
    "icelandic": ("is", "is-IS-GudrunNeural"),
    "irish": ("ga", "ga-IE-OrlaNeural"),
    "welsh": ("cy", "cy-GB-NiaNeural"),
    "belarusian": ("be", "en-US-AriaNeural"),
    "bosnian": ("bs", "hr-HR-GabrijelaNeural"),
    "corsican": ("co", "fr-FR-DeniseNeural"),
    "esperanto": ("eo", "en-US-AriaNeural"),
    "frisian": ("fy", "nl-NL-ColetteNeural"),
    "luxembourgish": ("lb", "de-DE-KatjaNeural"),
    "maltese": ("mt", "en-US-AriaNeural"),
    "scots gaelic": ("gd", "en-US-AriaNeural"),
    "yiddish": ("yi", "en-US-AriaNeural"),

    # === MIDDLE EASTERN LANGUAGES ===
    "arabic": ("ar", "ar-EG-SalmaNeural"),
    "hebrew": ("iw", "he-IL-AvriNeural"),
    "persian": ("fa", "fa-IR-DilaraNeural"),
    "pashto": ("ps", "ps-AF-LatifaNeural"),
    "kurdish kurmanji": ("ku", "hi-IN-MadhurNeural"),
    "kurdish sorani": ("ckb", "hi-IN-MadhurNeural"),
    "azerbaijani": ("az", "az-AZ-BanuNeural"),
    "georgian": ("ka", "ka-GE-EkaNeural"),
    "kazakh": ("kk", "kk-KZ-AigulNeural"),
    "kyrgyz": ("ky", "en-US-AriaNeural"),
    "tajik": ("tg", "en-US-AriaNeural"),
    "turkmen": ("tk", "en-US-AriaNeural"),
    "uyghur": ("ug", "en-US-AriaNeural"),
    "uzbek": ("uz", "uz-UZ-MadinaNeural"),
    "tatar": ("tt", "en-US-AriaNeural"),

    # === AFRICAN LANGUAGES ===
    "swahili": ("sw", "sw-KE-ZuriNeural"),
    "amharic": ("am", "am-ET-MekdesNeural"),
    "hausa": ("ha", "ha-NG-AminaNeural"),
    "yoruba": ("yo", "yo-NG-AbiolaNeural"),
    "igbo": ("ig", "ig-NG-ChinonsoNeural"),
    "somali": ("so", "so-SO-UbaxNeural"),
    "zulu": ("zu", "zu-ZA-ThandoNeural"),
    "afrikaans": ("af", "af-ZA-AdriNeural"),
    "xhosa": ("xh", "xh-ZA-NovelaneNeural"),
    "bambara": ("bm", "en-US-AriaNeural"),
    "chichewa": ("ny", "en-US-AriaNeural"),
    "ewe": ("ee", "en-US-AriaNeural"),
    "kinyarwanda": ("rw", "en-US-AriaNeural"),
    "lingala": ("ln", "en-US-AriaNeural"),
    "luganda": ("lg", "en-US-AriaNeural"),
    "oromo": ("om", "en-US-AriaNeural"),
    "sepedi": ("nso", "en-US-AriaNeural"),
    "sesotho": ("st", "en-US-AriaNeural"),
    "shona": ("sn", "en-US-AriaNeural"),
    "tigrinya": ("ti", "en-US-AriaNeural"),
    "tsonga": ("ts", "en-US-AriaNeural"),
    "twi": ("ak", "en-US-AriaNeural"),

    # === CENTRAL & SOUTH AMERICAN LANGUAGES ===
    "quechua": ("qu", "es-PE-CamilaNeural"),
    "guarani": ("gn", "es-PY-MarioNeural"),
    "aymara": ("ay", "es-BO-MarceloNeural"),
    "haitian creole": ("ht", "en-US-AriaNeural"),

    # === PACIFIC LANGUAGES (In Google Translate list) ===
    "maori": ("mi", "en-US-AriaNeural"),
    "hawaiian": ("haw", "en-US-AriaNeural"),
    "samoan": ("sm", "en-US-AriaNeural"),

    # === OTHER LANGUAGES ===
    "latin": ("la", "en-US-AriaNeural"),
    "malagasy": ("mg", "en-US-AriaNeural"),
    "meiteilon manipuri": ("mni-Mtei", "hi-IN-MadhurNeural"),
    "mizo": ("lus", "hi-IN-MadhurNeural"),
    "krio": ("kri", "en-US-AriaNeural"),
    "ilocano": ("ilo", "en-US-AriaNeural"),
    "armenian": ("hy", "en-US-AriaNeural"),
    "basque": ("eu", "en-US-AriaNeural"),
    "galician": ("gl", "en-US-AriaNeural"),
}


# ---------------------------------------------------------
# COUNTRY NAMES (DISPLAY ONLY)
# ---------------------------------------------------------

LANGUAGE_COUNTRIES = {
    "afrikaans": "South Africa",
    "albanian": "Albania",
    "amharic": "Ethiopia",
    "arabic": "Saudi Arabia",
    "armenian": "Armenia",
    "assamese": "India",
    "aymara": "Bolivia",
    "azerbaijani": "Azerbaijan",
    "bambara": "Mali",
    "basque": "Spain",
    "belarusian": "Belarus",
    "bengali": "India / Bangladesh",
    "bhojpuri": "India",
    "bodo": "India",
    "bosnian": "Bosnia and Herzegovina",
    "bulgarian": "Bulgaria",
    "cebuano": "Philippines",
    "chichewa": "Malawi",
    "chinese simplified": "China",
    "chinese traditional": "Taiwan",
    "corsican": "France",
    "croatian": "Croatia",
    "czech": "Czech Republic",
    "danish": "Denmark",
    "dhivehi": "Maldives",
    "dogri": "India",
    "dutch": "Netherlands",
    "english": "United States / United Kingdom / India",
    "esperanto": "International",
    "estonian": "Estonia",
    "ewe": "Ghana",
    "filipino": "Philippines",
    "finnish": "Finland",
    "french": "France",
    "frisian": "Netherlands",
    "galician": "Spain",
    "georgian": "Georgia",
    "german": "Germany",
    "greek": "Greece",
    "guarani": "Paraguay",
    "gujarati": "India",
    "haitian creole": "Haiti",
    "hausa": "Nigeria",
    "hawaiian": "United States",
    "hebrew": "Israel",
    "hindi": "India",
    "hmong": "China",
    "hungarian": "Hungary",
    "icelandic": "Iceland",
    "igbo": "Nigeria",
    "ilocano": "Philippines",
    "indonesian": "Indonesia",
    "irish": "Ireland",
    "italian": "Italy",
    "japanese": "Japan",
    "javanese": "Indonesia",
    "kannada": "India",
    "kashmiri": "India",
    "kazakh": "Kazakhstan",
    "khmer": "Cambodia",
    "kinyarwanda": "Rwanda",
    "konkani": "India",
    "korean": "South Korea",
    "krio": "Sierra Leone",
    "kurdish kurmanji": "Turkey",
    "kurdish sorani": "Iraq",
    "kyrgyz": "Kyrgyzstan",
    "lao": "Laos",
    "latin": "Vatican",
    "latvian": "Latvia",
    "lingala": "DR Congo",
    "lithuanian": "Lithuania",
    "luganda": "Uganda",
    "luxembourgish": "Luxembourg",
    "macedonian": "North Macedonia",
    "maithili": "India",
    "malagasy": "Madagascar",
    "malay": "Malaysia",
    "malayalam": "India",
    "maltese": "Malta",
    "maori": "New Zealand",
    "marathi": "India",
    "meiteilon manipuri": "India",
    "mizo": "India",
    "mongolian": "Mongolia",
    "myanmar burmese": "Myanmar",
    "nepali": "Nepal",
    "norwegian": "Norway",
    "odia": "India",
    "oromo": "Ethiopia",
    "pashto": "Afghanistan",
    "persian": "Iran",
    "polish": "Poland",
    "portuguese": "Portugal / Brazil",
    "punjabi": "India",
    "quechua": "Peru",
    "romanian": "Romania",
    "russian": "Russia",
    "samoan": "Samoa",
    "sanskrit": "India",
    "santhali": "India",
    "scots gaelic": "Scotland",
    "sepedi": "South Africa",
    "serbian": "Serbia",
    "sesotho": "Lesotho",
    "shona": "Zimbabwe",
    "sindhi": "India / Pakistan",
    "sinhala": "Sri Lanka",
    "slovak": "Slovakia",
    "slovenian": "Slovenia",
    "somali": "Somalia",
    "spanish": "Spain",
    "sundanese": "Indonesia",
    "swahili": "Kenya",
    "swedish": "Sweden",
    "tajik": "Tajikistan",
    "tamil": "India",
    "tatar": "Russia",
    "telugu": "India",
    "thai": "Thailand",
    "tibetan": "China",
    "tigrinya": "Eritrea",
    "tsonga": "South Africa",
    "turkish": "Turkey",
    "turkmen": "Turkmenistan",
    "twi": "Ghana",
    "ukrainian": "Ukraine",
    "urdu": "Pakistan",
    "uyghur": "China",
    "uzbek": "Uzbekistan",
    "vietnamese": "Vietnam",
    "welsh": "Wales",
    "xhosa": "South Africa",
    "yiddish": "Israel",
    "yoruba": "Nigeria",
    "zulu": "South Africa",
}